package com.digitalfemsa.tit.lending.job.template.dynamodb.entity;

import com.digitalfemsa.tit.lending.job.template.dynamodb.entity.converter.CompositeKeyConverter;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.experimental.SuperBuilder;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbConvertedBy;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSortKey;

import java.time.Instant;

/**
 * Entity class.
 */
@Data
@SuperBuilder
@DynamoDbBean
@NoArgsConstructor
public abstract class Entity {

    /**
     * Primary key.
     */
    @Getter(onMethod = @__({
            @DynamoDbPartitionKey,
            @DynamoDbConvertedBy(CompositeKeyConverter.class)
    }))
    protected CompositeKey pk;

    /**
     * Sort key.
     */
    @Getter(onMethod = @__({
            @DynamoDbSortKey,
            @DynamoDbConvertedBy(CompositeKeyConverter.class)
    }))
    protected CompositeKey sk;

    /**
     * Created date time.
     */
    @Setter
    @Getter
    protected Instant createdDateTime;

    /**
     * Last modified date time.
     */
    @Setter
    @Getter(onMethod = @__({
            @DynamoDbAutoGeneratedTimestampAttribute
    }))
    protected Instant lastModifiedDateTime;

}
